-- Enable the vectorscale extension
CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;

-- Create the embeddings table
CREATE TABLE IF NOT EXISTS embeddings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question TEXT,
    answer TEXT,
    category TEXT,
    embedding VECTOR(1536)
);

-- Create the StreamingDiskANN index
CREATE INDEX IF NOT EXISTS embeddings_idx ON embeddings
USING diskann (embedding);