-- Enable the vectorscale extension
CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;

-- Create the faq_embedding table
CREATE TABLE IF NOT EXISTS faq_embedding (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    question TEXT,
    answer TEXT,
    category TEXT,
    embedding VECTOR(1536)
);

-- Create the StreamingDiskANN index
CREATE INDEX IF NOT EXISTS faq_embedding_idx ON faq_embedding
USING diskann (embedding);